-------------------------------------------------------
--
-- Модуль 11
-- Демонстрация 3
-- Общие табличные выражения (Common Table Expressions, CTE)
--
-------------------------------------------------------

-- 1. CTE 
WITH CTE_year AS
	(
	SELECT EXTRACT(YEAR FROM orderdate) AS orderyear, custid
	FROM sales.orders
	)
SELECT orderyear, COUNT(DISTINCT custid) AS cust_count
FROM CTE_year
GROUP BY orderyear;


---------------------------------------------------------------------
-- 2. Заполнение значениями "на лету"

WITH cte_products (pid, pname, price, category) AS (
  VALUES
    (1, 'iPhone 15', 999.99, 'Electronics'),
    (2, 'MacBook Pro', 2499.99, 'Electronics'),
    (3, 'Coffee Mug', 15.50, 'Home'),
    (4, 'Programming Book', 49.99, 'Books'),
    (5, 'T-Shirt', 25.00, 'Clothing'),
    (6, 'Headphones', 199.99, 'Electronics'),
    (7, 'Desk Lamp', 45.75, 'Home')
)
SELECT * FROM cte_products;


WITH cte_products AS (
  SELECT 
    'Products ' || n as pname,
    (random() * 1000)::numeric(10,2) as price,
    floor(random() * 100)::int as qty,
    CASE (n % 3)
      WHEN 0 THEN 'Electronics'
      WHEN 1 THEN 'Books'
      ELSE 'Home'
    END as category
  FROM generate_series(1, 10) as n
)
SELECT pname, price, qty, category  FROM cte_products;

-- * аналогично наследуемая таблица (select from select)
SELECT *
FROM (
  VALUES
    (1, 'iPhone 15', 999.99, 'Electronics'),
    (2, 'MacBook Pro', 2499.99, 'Electronics'),
    (3, 'Coffee Mug', 15.50, 'Home')
) AS products(pid, pname, price, category);

SELECT pname, price, qty, category
FROM (
  SELECT 
    'Products ' || n as pname,
    (random() * 1000)::numeric(10,2) as price,
    floor(random() * 100)::int as qty,
    CASE (n % 3)
      WHEN 0 THEN 'Electronics'
      WHEN 1 THEN 'Books'
      ELSE 'Home'
    END as category
  FROM generate_series(1, 10) as n
) as products;


---------------------------------------------------------------------
--
-- 3. (* Optional) Recursive CTE
-- Сотрудники и их подчиненные в иерархии
--
---------------------------------------------------------------------
WITH RECURSIVE EmpOrg_CTE AS
(SELECT empid, mgrid, lastname, firstname --anchor query
	FROM hr.employees
WHERE empid = 2 --  `top` of tree. Сотрудник, для которого будут отображены подчиненные в иерархии
UNION ALL
SELECT child.empid, child.mgrid, child.lastname, child.firstname -- рекурсия Employees x EmpOrg_CTE
	FROM EmpOrg_CTE AS parent --
	JOIN hr.employees AS child
	ON child.mgrid=parent.empid
)
SELECT empid, mgrid, lastname, firstname
FROM EmpOrg_CTE;


---------------------------------------------------------------------
--
-- 4. (** Optional) Изменение данных в CTE
--
---------------------------------------------------------------------

-- 4.1 (создание таблиц для демонстрации и заполнение данными)

CREATE TABLE public.production -- Основная таблица
(
pid INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
pname varchar(100) NOT NULL,
pdate timestamp NOT NULL
);

CREATE TABLE public.production_log -- Таблица 'журнала'
(
pid INT NOT NULL,
pname varchar(100) NOT NULL,
pdate timestamp NOT NULL,
modifiedon timestamp DEFAULT NOW() NOT NULL,
modifiedby varchar(100) DEFAULT session_user NOT NULL
);

-- 4.2 данные с 1 мая 2023 по 01 декабря 2023
INSERT INTO public.production (pname, pdate)
VALUES ('Product' || FLOOR(RANDOM() * 1000 + 1)::int::varchar(10), 
	generate_series('2023-05-01'::timestamp, '2023-12-01'::timestamp, '5 hours'::interval))

SELECT * FROM public.production; 

--
-- 4.3 используем CTE для перемещения данных: удаление из public.production и добавление в public.production_log
WITH CTE_move_data AS (
    DELETE FROM public.production
    WHERE
        pdate >= '20231001' AND -- удаление данных за октябрь 2023
        pdate < '20231101'
    RETURNING * -- 
)
INSERT INTO public.production_log
SELECT * FROM CTE_move_data;

-- 4.4 Проверяем, что данные за октябрь 2023 попали в таблицу лога
SELECT * FROM public.production_log;

-- и были удалены из основной таблицы
SELECT * FROM public.production 
 WHERE
        pdate >= '20231001' AND 
        pdate < '20231101';

-- 4.5 Удаление таблиц
DROP TABLE IF EXISTS public.production;
DROP TABLE IF EXISTS public.production_log;



---------------------------------------------------------------------
--
-- 5. (*** Optional) MATERIALIZED
--
---------------------------------------------------------------------

EXPLAIN -- Обычный запрос: информация о проданных товарах с номером 14 в кол-ве от 6 шт.
SELECT * FROM sales.orderdetails
WHERE productid = 14 AND qty > 5;

EXPLAIN
WITH yy AS -- инструкция NOT MATERIALIZED - значение по умолчанию
NOT MATERIALIZED -- запрос в CTE выполняется как часть одного большого запроса
( SELECT * FROM sales.orderdetails WHERE  qty > 5 )
SELECT * FROM yy WHERE productid = 14;

EXPLAIN
WITH yy 
AS MATERIALIZED -- сначала явно выполнится запрос в CTE
( SELECT * FROM sales.orderdetails WHERE  qty > 5 )
SELECT * FROM yy WHERE productid = 14;