-------------------------------------------------------
--
-- Модуль 9
-- Демонстрация 1
-- Обзор функций агрегирования
--
-------------------------------------------------------

-- 1. Примеры функций агрегирования с разными типами данных
-- numeric
SELECT AVG(UnitPrice::numeric), MIN(qty), MAX(discount)
FROM sales.orderDetails;

-- varchar
SELECT MIN(shipcity) as first_territory, MAX(shipcity) as last_territory
FROM sales.orders;

SELECT STRING_AGG(categoryname, ', ') as all_categories
FROM production.categories;

-- datetime
SELECT MIN(OrderDate) AS earliest_order, MAX(OrderDate) AS latest_order
FROM sales.orders;

-- Ошибка - нет явного GROUP BY
SELECT orderid, productid, MIN(qty), MAX(discount)
FROM sales.orderDetails;

-- DISTINCT с функциями агрегирования
SELECT EXTRACT (YEAR FROM OrderDate) AS order_year,
COUNT(custid) as all_customers,
COUNT(DISTINCT custid) as unique_customers
FROM sales.orders
GROUP BY EXTRACT (YEAR FROM OrderDate);



-- 2. NULL и функции агрегирования

-- shipregion содержит NULLs в Sales.Orders
SELECT DISTINCT shipregion
FROM sales.orders
ORDER BY shipregion;

-- MIN, MAX и COUNT пропускают NULL, но не COUNT(*)
SELECT MIN(shipregion) AS A_region, MAX(shipregion) AS Z_region, 
COUNT(shipregion) AS countRegions, COUNT(*) AS COUNT_all
FROM sales.orders;

-- 3. Тестирование на NULL

-- 1. Тестовая таблица t1
CREATE TABLE public.t1(
	c1 INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
	c2 INT NULL);

INSERT INTO public.t1(c2)
VALUES(NULL),(10),(20),(30),(40),(50);

-- Сождержимое t1
SELECT c1, c2
FROM public.t1;

-- AVG и aritmetic average (SUM/COUNT)
SELECT SUM(c2) AS sum_nonnulls, COUNT(*) AS count_all_rows, 
COUNT(c2)AS count_nonnulls, AVG(c2) AS avgC2, (SUM(c2)/COUNT(*)) AS arith_avg
FROM public.t1;

-- Удаление таблицы
DROP TABLE public.t1;

-- 2. Тестовая таблица t2
CREATE TABLE public.t2
    (
      c1 INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
      c2 INT NULL
    );

INSERT INTO public.t2(c2)
VALUES(1),(10),(1),(NULL),(1),(10),(1),(NULL),(1),(10),(1),(10);

-- Сождержимое t2
SELECT c1, c2
FROM public.t2;

-- AVG vs замена NULL на 0
SELECT AVG(c2) AS AvgWithNULLs, AVG(COALESCE(c2,0)) AS AvgWithNULLReplace
FROM public.t2;

-- Удаление таблицы
DROP TABLE public.t2;