-------------------------------------------------------
--
-- Модуль 9
-- Демонстрация 1
-- Обзор функций агрегирования
--
-------------------------------------------------------

-- 1. Примеры функций агрегирования с разными типами данных
-- numeric
SELECT AVG(unitprice), MIN(qty), MAX(discount)
FROM sales.orderDetails;

-- общая сумма продаж за все время работы магазина
SELECT SUM(unitprice*qty) as total
FROM sales.orderDetails;

-- varchar
SELECT MIN(shipcity) as first_territory, MAX(shipcity) as last_territory
FROM sales.orders;

-- datetime
SELECT MIN(OrderDate) AS earliest_order, MAX(OrderDate) AS latest_order
FROM sales.orders;

-- STRING_AGG: сложение строк
SELECT STRING_AGG(categoryname, ', ') as all_categories
FROM production.categories;

-- *** Категории со списком продуктов в виде JSON
SELECT 
    c.categoryid,
    c.categoryname,
    json_agg(
        json_build_object(
            'id', p.productid,
            'name', p.productname,
            'price', p.unitprice
        )
    ) AS products
FROM production.categories c
LEFT JOIN production.products p ON c.categoryid = p.categoryid
GROUP BY c.categoryid, c.categoryname
ORDER BY c.categoryid;


-- DISTINCT с функциями агрегирования
SELECT COUNT(country) as allcust, COUNT(DISTINCT country) as unique_countries
FROM sales.customers;

SELECT DISTINCT country 
FROM sales.customers; -- 21 страна


-- Ошибка - нет явного GROUP BY
SELECT orderid, productid, MIN(qty), MAX(discount)
FROM sales.orderDetails;


-------------------------------------------------------
-- 2. NULL и функции агрегирования

-- shipregion содержит NULLs в Sales.Orders
-- MIN, MAX и COUNT пропускают NULL, но не COUNT(*)
SELECT MIN(shipregion) AS A_region, MAX(shipregion) AS Z_region, 
COUNT(shipregion) AS count_Regions, 
COUNT(DISTINCT shipregion) AS unique_Regions, 
COUNT(*) AS COUNT_all
FROM sales.orders;


-- 3. Тестирование на NULL

-- 1. Тестовая таблица t1
CREATE TABLE public.t1(
	c1 INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
	c2 INT NULL);

INSERT INTO public.t1(c2)
VALUES(NULL),(10),(20),(30),(40),(50);

-- Содержимое t1
SELECT c1, c2
FROM public.t1;

-- AVG и arithmetic average (SUM/COUNT)
SELECT SUM(c2) AS sum_nonnulls, COUNT(*) AS count_all_rows, 
COUNT(c2)AS count_nonnulls, AVG(c2) AS avgC2, (SUM(c2)/COUNT(*)) AS arith_avg
FROM public.t1;

-- AVG и замена NULL на 0 с помощью COALESCE
SELECT SUM(c2) AS sum_nonnulls, COUNT(*) AS count_all_rows, 
COUNT(c2)AS count_nonnulls, AVG(c2) AS avgC2, AVG(COALESCE(c2,0)) AS AvgWithNULLReplace
FROM public.t1;


-- Удаление таблицы
DROP TABLE public.t1;