-------------------------------------------------------
--
-- Модуль 7
-- Демонстрация 2
-- IDENTITY и SEQUENCE
--
-------------------------------------------------------

-- Информация о таблице production.categories
-- столбец categoryid имеет дополнительное свойство: generated by default as identity
-- \d production.categories
--                                         Таблица "production.categories"
--   Столбец    |          Тип           | Правило сортировки | Допустимость NULL |           По умолчанию
----------------+------------------------+--------------------+-------------------+----------------------------------
-- categoryid   | integer                |                    | not null          | generated by default as identity
-- categoryname | character varying(15)  |                    | not null          |
-- description  | character varying(200) |                    | not null          |


-- Список последовательностей на схеме production
-- \ds production.*
--                            Список отношений
--   Схема    |            Имя            |        Тип         | Владелец
--------------+---------------------------+--------------------+----------
-- production | categories_categoryid_seq | последовательность | postgres
-- production | products_productid_seq    | последовательность | postgres
-- production | suppliers_supplierid_seq  | последовательность | postgres

-- categories_categoryid_seq - объект последовательность, который соответствует столбцу с IDENTITY


-- Получение следующего значения
SELECT nextval('production.categories_categoryid_seq');

-- Получение текущего значения
SELECT currval('production.categories_categoryid_seq');

-- Установка текущего значения
SELECT setval ('production.categories_categoryid_seq', 100);

-- При вставке новой строки в production.categories можно пропустить categoryid
-- categoryid = 100 + 1
INSERT INTO production.categories (categoryname, description)
VALUES ('Mod07', 'Test Identity');

SELECT * FROM production.categories;

-- Удаляем новую категорию categoryid = 101
DELETE FROM production.categories WHERE categoryid = 101;

-- Устанавливаем "исходное" значение последовательности 
SELECT setval ('production.categories_categoryid_seq', 8);